# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python coverage

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        git submodule update --init
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build coverage using pytest-cov
      run: |
        pip install -r requirements-dev.txt
        pytest --cov=crafting --cov-report=xml tests
    - name: Upload coverage-report to codacy
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage.xml